// Script to add homes to the database
const mongoose = require('mongoose');
const schemas = require('./schemas.js');
let Home = schemas.Home;

mongoose.connect('mongodb://localhost/applehomes');

const homeArray = [
  {
    address: '527 Windsor Road, Arcadia, CA 91007',
    title: 'Beautiful Arcadia Home in Quiet Neighborhood',
    link: 'https://www.airbnb.com/rooms/10498164',
    summary: 'This home near 210 freeway convent. Features two queen size bedrooms on the second floor. Both contains a very cozy queen size double bed with memory form mattress and pillow.',
    description: 'The house is Ranch-style, has two bedrooms, both including a queen sized bed. The second floor of the private space, clean and tidy, the bed is soft and comfortable, cooking convenience, washing hot water, quiet environment, easy parking, convenient transportation. 10 minutes walk. It is a few minutes drive to Chinese supermarkets, cinemas malls, hospitals and hotels. 2 rooms can accommodate 2-4 people for small families to travel to rent. The location is close to big shopping mall and not far from the 210 free way. It is comfy house to stay for vacation. The room is nice and clean. You are given access to two bedrooms in a three bedroom house.',
    access: 'Full access to their respective rooms within the house, located on the second story of the building. Guests may also use rest of living space within the house including: Living room, kitchen (this includes also cookware, utensils, plates, etc).',
    neighborhood: 'Our house is extremely close to the 210 Freeway. The house is close to the park and the golf course, the traffic will be quiet, from the bank, post office, restaurant, light rail station, bus station. Airport 40 minutes drive to Universal Studios, Hollywood. Disneyland 30 minutes by car.',
    transportation: 'On the 210 high speed, take the light rail and the bus will be to Los Angeles Airport about 40 minutes to Universal Studios Hollywood and Disneyland 30 minutes by car. A few minutes to reach the nearby banks, post offices, restaurants, hotels, barber shop , The Chinese supermarket, the school library, the racecourse, the hospital, the shops, the department stores, the cinemas, the city hall, etc. Drive to the Gulf of Ireland about 60 minutes by car to the Las Vegas about 4 hours by car.good location close shopping mall Park, golf course',
    notes: 'You may call, text, or contact us through AirBNB. We speak both Mandarin and English. Please lock the doors upon exiting or checking out of the building. Please also keep the house clean.',
    area: 'Arcadia',
    price: 96,
    people: 4,
    beds: 2,
    bedrooms: 2,
    bathrooms: 1,
    fullHome: false,
    privateRoom: true,
    privateBath: true
  },
  {
    address: '1937 Strathmore Ave, San Gabriel, CA 91776',
    title: 'High Bedding 2 Rooms, Suitable for Family in San Gabriel',
    link: 'https://www.airbnb.com/rooms/12798616',
    summary: 'This listing is for one bedroom in a 5 bedroom house',
    description: 'This room has a queen size bed , and can accommodate 2 guests, Great location, walking distance to shopping and restaurants. The mattress and bedding are completely accord with human body sleep designed comfortable activities, absolutely let you have a high-quality sleep experience. The room is also equipped with a small refrigerator, kitchen dining room guests can be used at any time. Kitchen double refrigerator capacity. Inside / outside the room for guest parking. You can walk to the Chinese supermarket shopping malls, restaurants, this is  most concentrated residential area.',
    access: 'Access to their respective rooms and rest of living space including: living room, kitchen, washer, dryer, parking space, etc.',
    neighborhood: 'Location is very convenient with several Chinese business and locations around the area. There are several around the Chinese supermarket, as well as a large variety of restaurants around there several star hotels. Enjoying a vacation with friends can be convenient. Located near the 10th high-speed travel, it is convenient to travel to many places, including: the heart of LA, Disneyland, Hollywood, and other major cities and sites.',
    transportation: 'Being near the freeway, our location is very convenient to travel to many places. There are bus stations located nearby and the airport only takes about 35 minutes to get to. To Hollywood Universal Pictures, Disneyland about 25-30 minutes by car.',
    notes: 'You may contact me via call, text, or e-mail, or through airbnb. Able to speak both Mandarin and English. Please lock the door when you leave, and close the garage door as well. Keep the garage remote and house keys secure as well please.',
    area: 'San Gabriel',
    price: 99,
    people: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    fullHome: false,
    privateRoom: true,
    privateBath: false
  },
  {
    address: '306 West Lime Avenue, Monrovia, CA 91016',
    title: 'Peaceful and Comfortable Private Monrovia Bedroom',
    link: 'https://www.airbnb.com/rooms/13639457',
    summary: 'Double story house with 2 private rooms available for use. There is plenty of privacy and includes 1.5 bathrooms as well. Comes equipped with high speed internet access, dedicated parking space, hotel standard bedding, as well as cooking utensils, equipment, and laundry. Convenient and comfortable, as well as being on minutes away from Old Town Monrovia. Every Friday, experience the well known Monrovia farmers market and entertainment only minutes away from your doorstep.',
    description: 'Space independence, this house has three rooms, the master bedroom when there is no time to live. So the entire house from the parking garage, kitchen dining room, living room laundry room easy to use. All meal cooking utensils are complete. A 10-minute walk from Monrovia\'s old town\'s central business street. On the street cinema supermarkets and a variety of styles of cuisine are everywhere. 2 rooms close together, bedding clean and comfortable. The rooms are warm and romantic.',
    access: 'Full access to the house and their respective rooms.',
    neighborhood: 'Only a few minutes walk to the library, park, cinema, supermarket, gymnasium, and bank. As well as a variety of restaurants nearby to cater to your tastes. Everything you need is only a few minutes walk. Experience american culture by partaking in the local festivities every Friday at the night market in Old Town Monrovia. Located in a quiet and friendly neighborhood, unwind in the relaxed atmosphere the city has to offer.',
    transportation: 'Location is only a few minutes away from the 210 high-speed freeway. The gold line metro is only a few minutes away by car, or about 18 minutes walking. The Los Angeles International Airport is about 45 minutes,  Hollywood Universal Studios is about 30 minutes away, and Disneyland is about 45 minutes away',
    notes: 'You may contact me via call, text, e-mail, or through airbnb. Able to speak both Mandarin and English. Please lock the door when you leave.',
    area: 'Monrovia',
    price: 159,
    people: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1.5,
    fullHome: true,
    privateRoom: true,
    privateBath: true
  },
  {
    address: '600 North Atlantic Blvd Ut 309, Monterey Park, CA 91754',
    title: '3 Bedroom Modern Apartment in Monterey Park',
    link: 'https://www.airbnb.com/rooms/15414529',
    summary: 'New Condo in City of Monterey Park. Atlantic Time Square brings excitement like New York City Time Square& more. This urban lifestyle featuring 210 luxury condo units with attractive Paseo design. Residence unit from 2nd floor to 6th floor. Unique features includes: modern spacious living area and bath room; large kitchen space; granite counter tops; top of the line stainless appliances; washer and dryer space; circular design entrance. Balconies in all units. Large windows for great views.',
    description: 'This house it is easily accommodates a whole family or roommates to share ,located at the intersection of Atlantic Blvd and Hellman and just one block from freeway 10.',
    access: 'Full private access to entire apartment.',
    neighborhood: 'This is Charming and modern area. Club house, swimming pool and courtyard are some amenities for residence. Ground level gives you endless amenities, 24 house fitness center, restaurants, Supermarket,shopping, AMC Theaters and much more.',
    transportation: 'Easy access to 10 FWY 2 minutes to go to Highway 10, about 30 minutes to Los Angeles International Airport, about 26 minutes to Universal Studios, about 40 minutes to Disneyland. From Highway 10 to the east to the Outlet Mall, and Las Vegas. West to the city center and so on.',
    notes: '1)Please lock the doors when you leave the apartment. 2)Clothes may not be hanged outside on the balcony. 3)Please clean cookware and utensils after use. 4)Turn off water and gas when not in use. 5)Please turn off the lights and central AC when you leave. 6)Please do not leave children unsupervised on the balcony in case of injury. You may contact us through phone, text, or airbnb message. We speak both English and Mandarin.',
    area: 'Monterey Park',
    price: 238,
    people: 6,
    bedrooms: 3,
    beds: 3,
    bathrooms: 2.5,
    fullHome: true,
    privateRoom: true,
    privateBath: true
  },
  {
    address: '304 West Lime Avenue Unit 1, Monrovia, CA 91016',
    title: 'Quiet and Romantic Townhome located in Monrovia',
    link: 'https://www.airbnb.com/rooms/13536798',
    summary: 'Our convenient and comfortable home is located near the heart of Old Town Monrovia. There, you can explore and dine on the many various styles of restaurants and food around, as well as spend a lovely evening date watching movies or walking around the park. The master bedroom is fully furnished with a large queen sized bed. Downstairs features a large and spacious living area perfect for work space as well as relaxation. Kitchen is fully equipped with cooking equipment, dishware, and utensils.',
    description: 'You\'ll be given access the master bedroom of our home. Comes complete with a private bathroom inside as well. Our space is located in a very quiet and family oriented neighborhood. You\'ll be given total peace and quiet to enjoy and relax all that the nearby streets have to offer. Being only a few minutes away by walk, Old Town Monrovia features a wide variety of activities and shops to enjoy. Every Friday, you\'ll be able to enjoy the Monrovia Old Town night market featuring an even more wide variety of street food, desserts, and hand made crafts. The streets become very bustling and lively, perfect for dates and casual hang outs with friends, while still remaining very quiet and peaceful during your stays at our home.',
    access: 'Full access to 1st floor and respective room on 2nd floor. Wi-Fi included.',
    neighborhood: 'Only a few minutes walk to the library, park, cinema, supermarket, gymnasium, and bank. As well as a variety of restaurants nearby to cater to your tastes. Everything you need is only a few minutes walk. Experience american culture by partaking in the local festivities every Friday at the night market in Old Town Monrovia. Located in a quiet and friendly neighborhood, unwind in the relaxed atmosphere the city has to offer.',
    transportation: 'Location is only a few minutes away from the 210 high-speed freeway. The gold line metro is only a few minutes away by car, or about 18 minutes walking. The Los Angeles International Airport is about 45 minutes,  Hollywood Universal Studios is about 30 minutes away, and Disneyland is about 45 minutes away.',
    notes: 'Please lock the door when you. Please turn off the lights if not in use. No pets. Non smoking Thank you. You may contact me via call, text, e-mail, or through airbnb. Able to speak both Mandarin and English.',
    area: 'Monrovia',
    price: 79,
    people: 3,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    fullHome: false,
    privateRoom: true,
    privateBath: true
  },
  {
    address: '304 West Lime Avenue Unit 2, Monrovia, CA 91016',
    title: 'Spacious and Cozy Townhome located in Monrovia',
    link: 'https://www.airbnb.com/rooms/17846344',
    summary: 'Our convenient and comfortable home is located near the heart of Old Town Monrovia. There, you can explore and dine on the many various styles of restaurants and food around, as well as spend a lovely evening date watching movies or walking around the park. The room is fully furnished with a large queen sized bed. Downstairs features a large and spacious living area perfect for work space as well as relaxation. Kitchen is fully equipped with cooking equipment, dishware, and utensils.',
    description: 'Our space is located in a very quiet and family oriented neighborhood. You\'ll be given total peace and quiet to enjoy and relax all that the nearby streets have to offer. Being only a few minutes away by walk, Old Town Monrovia features a wide variety of activities and shops to enjoy. Every Friday, you\'ll be able to enjoy the Monrovia Old Town night market featuring an even more wide variety of street food, desserts, and hand made crafts. The streets become very bustling and lively, perfect for dates and casual hang outs with friends, while still remaining very quiet and peaceful during your stays at our home.',
    access: 'Access to 1st story and their respective room on the 2nd floor. 1.5 Bathroom is shared if there are other quests. Wi-Fi included',
    neighborhood: 'Only a few minutes walk to the library, park, cinema, supermarket, gymnasium, and bank. As well as a variety of restaurants nearby to cater to your tastes. Everything you need is only a few minutes walk. Experience american culture by partaking in the local festivities every Friday at the night market in Old Town Monrovia. Located in a quiet and friendly neighborhood, unwind in the relaxed atmosphere the city has to offer.',
    transportation: 'Location is only a few minutes away from the 210 high-speed freeway. The gold line metro is only a few minutes away by car, or about 18 minutes walking. The Los Angeles International Airport is about 45 minutes,  Hollywood Universal Studios is about 30 minutes away, and Disneyland is about 45 minutes away.',
    notes: 'You may contact me via call, text, e-mail, or through airbnb. Able to speak both Mandarin and English. Please lock the door when you. Please turn off the lights if not in use. No pets. Non smoking. Thank you.',
    area: 'Monrovia',
    price: 79,
    people: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1.5,
    fullHome: false,
    privateRoom: true,
    privateBath: true
  },
  // {
  //   address: '165 Bonita St Unit A, Arcadia, CA 91006',
  //   link: '',
  //   summary: 'Arcadia City Center is within walking distance to the subway station and bus station. Schools, parks, gold courses, libraries are within walking distance as well. There are Chinese restaurants is in the vicinity of the supermarket. The house is in a very quiet neighborhood. There is a sofa/folding bed that is suitable for families and couples. It has its own private bathroom, kitchen, parking garage, and laundry.',
  //   description: 'Easy parking. Kitchen and laundry room are available for anyone to use. There are fragent fruit trees in the peaceful, quiet stone garden. There is a spacious living room.',
  //   access: 'Parking Garage, Laundry room, kitchen, dining room, living room, lounge, front and rear garden areas can be accessed.',
  //   neighborhood: 'Home in Arcadia, between the 1St and 2St, is a quiet place, within walking distance to the nearby school, Methodist Hospital, post office, Bank, Metro bus public transport, Park Golf course, and a variety of restaurants and Chinese supermarkets. Occasionally there will be American-style night market.',
  //   transportation: '5 minutes on the 210 Freeway, East Las Vegas, 35 minutes to downtown Los Angeles to the West. 45 minutes from the airport, about 35 minutes from Universal Studios Hollywood, about 45 minutes from Disneyland, about 50 minutes from auto outlet. A few minutes walk to a nearby subway station and bus station.',
  //   notes: 'Please lock the door and garage door when leaving. Turn off the gas stove in the kitchen, as well as the light. 12:00 minutes later on the cars cannot be parked on the roadside.',
  //   area: 'Arcadia',
  //   price: 999,
  //   people: 3,
  //   bedrooms: 1,
  //   beds: 1,
  //   bathrooms: 1,
  //   fullHome: true,
  //   privateRoom: true,
  //   privateBath: true
  // },
  // {
  //   address: '580 North Atlantic Boulevard Unit 213, Monterey Park, CA',
  //   link: '',
  //   summary: 'Beautiful and newly furnished hotel-esque living space located right above the lively Monterey Park Times Square. Enjoy comfort in our clean and comfortable living space perfect for families or groups. If you\'re in the mood for food; conveniently only a few minutes by walk, you may enjoy several varieties of Asian-themed restaurants to choose from right below. The times square also hosts a large selection of entertainment choices to choose such as a 24 hour gym, AMC cinema, and games to play.',
  //   description: 'Fully furnished 3 Bedroom, 2.5 Bathroom lovely home complete with new furniture, a large king and two queen sized beds. Kitchen is fully stacked with cooking equipment, dishes, and eating utensils.  Included is also: a complete washer and dryer set in the house, two private parking spaces, and free public swimming pool to enjoy for those upcoming hot days. Downstairs in the times square features a variety of food and entertainment choices only a few minutes walk.',
  //   access: 'Full private access to entire apartment.',
  //   neighborhood: 'Our lovely home is not only conveniently located next to the 10 high speed freeway, but also conveniently above a plaza hosting several forms of Asian-style cuisine and desserts. Not only cuisine, but there are several stores you can shop at, cafes to relax in, a 24 hour fitness gym for members, and also a large AMC theater. If you ever want to explore the heart of LA, we\'re only 20 minutes away by freeway. The apartment building also features a free public swimming pool available for apartment tenants and guests on the 3rd floor.',
  //   transportation: 'Easy access to 10 FWY 2 minutes to go to Highway 10, about 30 minutes to Los Angeles International Airport, about 26 minutes to Universal Studios, about 40 minutes to Disneyland. From Highway 10 to the east to the Outlet Mall, and Las Vegas. West to the city center and so on.',
  //   notes: 'You may contact us through phone, text, or Airbnb. We speak English and Mandarin. Please lock the door when you exit. Turn off all lights when not in use either. No Smoking. Thank you',
  //   area: 'Monterey Park',
  //   price: 999,
  //   people: 6,
  //   bedrooms: 3,
  //   beds: 3,
  //   bathrooms: 2.5,
  //   fullHome: true,
  //   privateRoom: true,
  //   privateBath: true
  // },
  {
    address: '50 Alice Street Unit C, Arcadia, CA 91006',
    title: 'Comfy and Convenient Apartment in Arcadia',
    link: 'https://www.airbnb.com/rooms/17846344',
    summary: 'This home features large rooms with clean and comfortable beds. We may had additional beds to accommodate more people. We also have makeup and bathroom facilities. If you are exploring the city, the home is within walking distance to the subway station. There is a post office, bank, Arcadia High School, libraries, park, and golf course all nearby. You will feel very secure in this home!',
    description: 'This home has enough space for a family. The apartment unit is beyond a gate so there is extra security in an already safe, peaceful, quiet neighborhood. There are specific parking spaces underground for the unit. Each bedroom has their own restroom. The master bedroom is very spacious.',
    access: 'Conveniently located Arcadia park golf course restaurants and shops. Come with two car parking garage.',
    neighborhood: 'The neighborhood is nice and quiet.',
    transportation: 'There are many plazas that are close by. The 210 freeway is only about 7 minutes away.',
    notes: 'You may contact us through phone, text, or Airbnb. We speak English and Mandarin. Please lock the door when you exit. Turn off all lights when not in use either. No Smoking. Thank you',
    area: 'Arcadia',
    price: 166,
    people: 6,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2.5,
    fullHome: true,
    privateRoom: true,
    privateBath: true
  },
  // {
  //   address: '550 North Atlantic Boulevard Unit 253, Monterey Park, CA 91754, US',
  //   link: '',
  //   summary: '',
  //   description: '',
  //   access: '',
  //   neighborhood: '',
  //   transportation: '',
  //   notes: '',
  //   area: 'Monterey Park',
  //   price: 169,
  //   people: 4,
  //   bedrooms: 1,
  //   beds: 1,
  //   bathrooms: 1,
  //   fullHome: true,
  //   privateRoom: true,
  //   privateBath: true
  // },
  {
    address: '50 Alice Unit D, Arcadia, CA 91006, US (Room 1)',
    title: 'Single room in Arcadia apartment',
    link: 'https://www.airbnb.com/rooms/15606255',
    summary: 'Comfortable, Warm, Tidy Arcadia Home Next to Parks',
    description: 'The room has a nice queen size bed that can be used by 2 people. The room is complete by décor and an office desk for recreational use. The bed itself has superior cooton beeding. There is a nice, cozy atmosphere that can be loved by anyone. The kitchen is available for anyone to use and is complete with kitchen amenities and utensils. A designated garage space is avaliable for guests. When you are done with the day, you may spend a calm evening in the park just a block away.',
    access: 'The house is very clean and cozy. White backdrops and windows brighten up the place to create a nice living atmosphere.',
    neighborhood: 'Very quiet and peaceful. There is a park down the street and many restaurants to check out near by. Guests would be happy with the calmness of the neighborhood.',
    transportation: 'The Santa Anita Mall is a couple minutes away. The I-210 Freeway is about 5 minutes away.  There are many plazas to check out that are only a couple minutes away from the home.',
    notes: 'When leaving the house, please make sure that all electronics and gas is off. Please make sure the all windows and doors are locked. The house has stairs, so please make sure to be aware of your footing. Smoking is not allowed.',
    area: 'Arcadia',
    price: 49,
    people: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 0.5,
    fullHome: false,
    privateRoom: true,
    privateBath: true
  },
  {
    address: '580 North Atlantic Blvd Unit 231 Monterey Park, CA 91754',
    title: 'Monterey Park Apartment in mixed Residential and Commercial Area',
    link: 'https://www.airbnb.com/rooms/18310838',
    summary: 'Luxurious Apartment Home with Fun Right Next Door',
    description: 'This apartment is cozy, clean, and private. The home is new and full of amenities to fill your and your family/ friends\' needs. Laundry and kitchen and living room are all accessible. The apartments are right next to a Chinese Plaza, where guests can watch movies, try different foods, play games, and do many more.',
    access: 'The home itself is cozy, tidy, calm and quiet. The house can be considered luxurious to some. The kitchen is very roomy. The living room is accessible to many people. The beds and bed rooms can fit at least 2 people.',
    neighborhood: 'Our lovely home is not only conveniently located next to the 10 high speed freeway, but also placed above a plaza hosting several forms of Asian-style cuisine and desserts. There are not only cuisine, but also several stores you can shop at, cafes to relax in, a 24 hour fitness gym for members, and a large AMC theater. If you ever want to explore the heart of LA, the apartment is only 20 minutes away through freeway. The apartment building also features a free public swimming pool available for apartment tenants and guests.',
    transportation: 'Easy access to 10 FWY 2 minutes to go to Highway I-10, about 30 minutes to Los Angeles International Airport, about 30 minutes to Universal Studios, about 40 minutes to Disneyland.',
    notes: 'You may contact us through phone, text, or Airbnb. We speak English and Mandarin. Please lock the door when you exit. Turn off all lights when not in use either. No Smoking. Thank you.',
    area: 'Monterey Park',
    price: 239,
    people: 6,
    bedrooms: 3,
    beds: 3,
    bathrooms: 2.5,
    fullHome: true,
    privateRoom: true,
    privateBath: true
  },
  // {
  //   address: '235 B W Walnut Ave, Monrovia, CA 91016',
  //   link: '',
  //   summary: 'Monrovia 2-room apartment for Rent, suitable for Family ',
  //   description: 'The home is located in the heart of the old town of Monrovia, where guests are a few minutes walk to the librarym street park, cinema, supermarkets, and restuarants. Every Friday night, there is a town festival held just for locals and are welcoming of tourists as well. The home itself is very cozy, spacious, clean and private. There are 2 parking spaces avliable for guests. The home comes with full amenities.',
  //   access: 'The house can accommodate up to 4 people. The entire home is available and accessible to the guests. The bedding is of high quality and will guarantee guests a wonderful sleep. The living room is spacious, especially for a family of 4. Every room has been clean and decorated for your appeal.',
  //   neighborhood: 'The Neighborhood is calm and quiet. It is only a few minutes walk to the library, park, cinema, supermarket, gymnasium, and bank. A variety of restaurants are nearby to cater to your tastes. Everything you need is only a few minutes walk. Everyday Friday night, there is a night market hosted by locals. It is wonderful place for a great shopping experience and to try different goods and food.',
  //   transportation: 'Old Town Monrovia is walking distance. The I-210 is only minutes away and will take you to most destinations of California. The airport is amount 30 minutes from the home.',
  //   notes: 'You may contact me via call, text, e-mail, or through airbnb. Able to speak both Mandarin and English. Please lock the door when you. Please turn off the lights if not in use. No pets. No smoking Thank you.',
  //   area: 'Monrovia',
  //   price: 120,
  //   people: 4,
  //   bedrooms: 1,
  //   beds: 2,
  //   bathrooms: 1,
  //   fullHome: true,
  //   privateRoom: true,
  //   privateBath: true
  // },
  {
    address: '731 South Del Mar Ave Unit D San Gabriel, CA 91776',
    title: 'Cozy 3 Bedroom Townhome Near Downtown LA',
    link: 'https://www.airbnb.com/rooms/16629180',
    summary: 'Spacious home with Elegant Atmosphere and Terrace',
    description: 'This home has a beautiful, lovely Terrance with elegant atmosphere. Our clean and tidy master bedroom is complete with an independent private bathroom. The location is near a Chinese Plaza, where there is the Chinese supermarket, restaurants and stores. All amenities, including washer and dryer, are avaliable for use.',
    access: 'The home itself is a very cozy, neat, and tidy space. The master room is has a beautiful bright atmosphere. A terrace gives you a view from the bedroom. It is a fairly modern space, with hardwoof floors and granite counter tops. The living room is filled with décor and amenities just for guest\'s convenience.',
    neighborhood: 'The location is next several Chinese business and locations around the area. There are several around the Chinese supermarket.A large variety of restaurants are around. Enjoying a meal with friends and family can be convenient. Located near the 10th high-speed travel, it is convenient to travel to many places, including: the heart of LA, Disneyland, Hollywood, and other major cities and sites.',
    transportation: 'Being near the freeway, our location is very convenient to travel to many places. There are bus stations located nearby and the airport only takes about 35 minutes to get to. To Hollywood Universal Pictures, Disneyland about 25-30 minutes by car.',
    notes: 'You may contact us via call, text, or e-mail, or through airbnb. Able to speak both Mandarin and English. Please lock the door when you leave, and close the garage door as well. Keep the garage remote and house keys secure as well please.',
    area: 'San Gabriel',
    price: 79,
    people: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    fullHome: false,
    privateRoom: true,
    privateBath: true
  },
  {
    address: '550 North Atlantic Boulevard Unit 353, Monterey Park, CA 91754, US',
    title: 'Quiet and Comfy Monterey Park apartment',
    link: 'https://www.airbnb.com/rooms/18559414',
    summary: 'Luxurious, High Serviced Apartments Complete with Private Rooms and Parking',
    description: 'The beautiful, bright apartments are complete with two cozy, lovely rooms, each with their own privacy. The house is very modern and new. It is filled with amenities. The apartments are located within a plaza, where guests can eat, watch movies, drink tea and coffee, and play games.',
    access: 'The house is new, clean, cozy, and modern. The windows give the home a nice bright atmosphere. It is very spacious and will fit a family of 4 very nicely. It is also convienent for two couples on a getaway trip. Guests will enjoy the beautiful marble countertops, comfortable bedding, and living room fill with decor. It is luxurious living at the minimal.',
    neighborhood: 'Our lovely home is not only conveniently located next to the 10 high speed freeway, but also placed above a plaza hosting several forms of Asian-style cuisine and desserts. There are not only cuisine, but also several stores you can shop at, cafes to relax in, a 24 hour fitness gym for members, and a large AMC theater. If you ever want to explore the heart of LA, the apartment is only 20 minutes away through freeway. The apartment building also features a free public swimming pool available for apartment tenants and guests.',
    transportation: 'Easy access to 10 FWY 2 minutes to go to Highway I-10, about 30 minutes to Los Angeles International Airport, about 30 minutes to Universal Studios, about 40 minutes to Disneyland.',
    notes: 'You may contact us through phone, text, or Airbnb. We speak English and Mandarin. Please lock the door when you exit. Turn off all lights when not in use either. No Smoking. Thank you.',
    area: 'Monterey Park',
    price: 199,
    people: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    fullHome: true,
    privateRoom: true,
    privateBath: true
  },
  {
    address: '306 South 1st Ave Arcadia, CA 91006 (Room 1)',
    title: 'Convenient and Quiet Apartment Located near Middle School',
    link: 'https://www.airbnb.com/rooms/16694387',
    summary: 'Calm, Quiet Arcadia 2 Bdrm Home',
    description: 'This is a Nice, Calm, and Quiet Arcadia home made for your appeal. This home is guaranteed to satisfy all your needs. The home itself is close to banks, restuarants, plazas, shopping mall, and freeway. All the rooms are very spacious and filled with amenities.',
    access: 'The rooms are bright and spacious. 2 rooms have 1 separate bathroom. All restrooms can be used. 2 rooms have desks and chairs, along with a balcony. The basement has plenty of parking spaces. The kitchen has enough room for a family to spend their time cooking. Guests will find the living room to spacious and decorated as well.',
    neighborhood: 'Very quiet and peaceful. There is a park down the street and many restaurants to check out near by. Guests would be happy with the calmness of the neighborhood.',
    transportation: 'The Santa Anita Mall is a couple minutes away. The I-210 Freeway is about 5 minutes away.  There are many plazas to check out that are only a couple minutes away from the home. LAX is about 30 minutes away. Disney and Universal Studio are about 30-45 minutes away.',
    notes: 'At any time by telephone, text messages, e-mail, interviews, etc. can be used. We can speak Chinese and English. The garbage must be packed in the garbage bag and thrown into the designated garbage delivery point. When leaving the home, please lock the door and bring the key.',
    area: 'Arcadia',
    price: 119,
    people: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1.5,
    fullHome: false,
    privateRoom: true,
    privateBath: true
  },
  {
    address: '600 North Atlantic Boulevard Unit 406, Monterey Park, CA 91754, US',
    title: 'Luxury Apartment located in Monterey Park with Pool',
    link: 'https://www.airbnb.com/rooms/19988388',
    summary: 'Modern Brand New luxury condo Like Hotel',
    description: 'New Condo in City of Monterey Park. Atlantic Time Square brings excitement like New York City Time Square& more. This urban lifestyle featuring 210 luxury condo units with attractive Paseo design. Residence unit from 2nd floor to 6th floor. Unique features includes: modern spacious living area and bath room; large kitchen space; granite counter tops; top of the line stainless appliances; washer and dryer space; circular design entrance. Balconies in all units. Large windows for great views & lig',
    access: 'This house it is easily accommodates a whole family or roommates to share ,located at the intersection of Atlantic Blvd and Hellman and just one block from freeway 10.',
    neighborhood: 'This is a charming and modern area. Club house, swimming pool and courtyard are only some of the activities guests may do. Ground level gives you endless activities, 24 house fitness center, restaurants, Supermarket,shopping, AMC Theaters and much more.',
    transportation: 'Easy access to 10 FWY 2 minutes to go to Highway 10, about 30 minutes to Los Angeles International Airport, about 26 minutes to Universal Studios, about 40 minutes to Disneyland. From Highway 10 to the east to the Outlet Mall, and Las Vegas. West to the city center and so on.',
    notes: '1)Please lock the doors when you leave the apartment. 2)Clothes may not be hanged outside on the balcony. 3)Please clean cookware and utensils after use. 4)Turn off water and gas when not in use. 5)Please turn off the lights and central AC when you leave. 6)Please do not leave children unsupervised on the balcony in case of injury.                                                     You may contact us through phone, text, or airbnb message. We speak both English and Mandarin.',
    area: 'Monterey Park',
    price: 219,
    people: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    fullHome: true,
    privateRoom: true,
    privateBath: true
  },
  {
    address: '2103 Cooley Place, Pasadena, CA 91104, US',
    title: 'Peaceful Remodeled Pasadena Home Near Freeway',
    link: 'https://www.airbnb.com/rooms/18509865',
    summary: 'Elegantly Newly Remodeled 3Br 2Bath Pasadena Home',
    description: 'Entire 3 bedroom, 2 bathroom newly remodeled spacious home located in Pasadena. The master bedroom is fully furnished with a large king sized bed, the second room comes with a queen sized bed. There is a twin sized sofa bed in the study can fit an additional person. The kitchen is fully stocked with all the necessary cooking utensils and equipment. Private parking is provided on the premises as well. Front and back garden. Convenient location being only a few minutes away from the 210 Freeway.',
    access: 'The house is deisgned for those who loves a small but cozy place. A new master bedroom has been added to the home. All the rooms have been repainted and furbished. The kitchen has a bright atmosphere and has a pantry attached that leads to the back yard. This luxurious 6,657 sqft home has recently been fully remodeled with new hardwood flooring and complete with new furniture and decor.',
    neighborhood: 'The Neighborhood is very nice and calm. It is beauitful and lovely to be a part of this neighborhood.',
    transportation: 'Old Town Pasadena is about 5-10 minutes away. It is filled with shopping centers, resutarants, outlets, and many more. The house is also about 5 minutes from the I-210 freeway. It is about 30 minutes from the airport and an hour from DisneyLand. Within minutes from the freeway, you\'ll be able to travel to all of the highlighted locations that LA has to offer.',
    notes: 'You may contact us through phone, text, or Airbnb. We speak English and Mandarin. Please lock the door when you exit. Turn off all lights when not in use either. Thank you',
    area: 'Pasadena',
    price: 199,
    people: 6,
    bedrooms: 3,
    beds: 2,
    bathrooms: 2,
    fullHome: true,
    privateRoom: true,
    privateBath: true
  },
  {
    address: '656 West Huntington Drive F2, Arcadia, CA 91007, United States',
    title: 'Cozy Apartment located in Arcadia suitable for Families',
    link: 'https://www.airbnb.com/rooms/19632648',
    summary: 'Lovely Neighborhood, Calm Home of Arcadia',
    description: 'This Townhouse unit is right across from the Santa Anita Mall and close by some of the best restaurants on Baldwin Ave. If you\'re looking for newly 2014 built unit with the convenience of what Arcadia has to offer, this is the home for you!',
    access: 'As you enter this tri-level home, you will be impressed with the vaulted ceiling over the formal living room which boasts dark hardwood throughout leading to the designer gourmet kitchen. A large island is the centerpiece of this kitchen which offers quartz countertops, mosaic backsplash, under cabinet lighting and upgraded dark cabinets with self closing drawers. The master bedroom provides ample space with closet organizers. Master bath includes luxurious stone surrounding the tub and frameless shower enclosure.',
    neighborhood: 'The home is located  at a town house condominium. It is very safe, quiet, and cozy. Neighbors are friendly and quiet.',
    transportation: 'Enjoy experiencing large commercial complexes, cinemas, gyms, racecourse, hospitals, schools, golf courses, parks, brand-name department stores and so on. It takes about 5 minutes to get on the I-210 freeway, which will get you just about anywhere. It is about 40 minutes from the LOs Angeles International Airport.',
    notes: 'You may contact us at any time. We speak Chinese and English. Please No Pets, and No Smoking.',
    area: 'Arcadia',
    price: 239,
    people: 6,
    bedrooms: 3,
    beds: 3,
    bathrooms: 2.5,
    fullHome: true,
    privateRoom: true,
    privateBath: true
  },
  {
    address: '1832 South Fifth Avenue Unit E, Monrovia, CA 91016, United States',
    title: 'Apartment in Monrovia with Netflix and Hulu',
    link: 'https://www.airbnb.com/rooms/19901109',
    summary: 'Elegant, Quiet, Clean, and Comfortable Monrovia Home. ',
    description: 'Beautiful condo in excellent condition. The location is very close to shopping centers , restaurant and markets. It has two large master suites. Guests will enjoy its bright and spacious living room and wide dinning area. Wood lamenated floors are in the living room with a cozy fireplace. Washer, dryer, and Refrigerator is included. Partially new paint downstairs and new paint on all bedrooms. One street away from the city of Arcadia.',
    access: 'It has vaulted ceilings, walk-in closet in master bedroom, bathroom has granite counter-top, entire home is tiled, remodeled kitchen with granite counter-tops, with newer appliances. Guests have access to private parking garage, laundry room, high speed WiFi network, kitchen dining room, and a complete dining tableware set.Very clean and cozy.',
    neighborhood: 'N/A',
    transportation: 'N/A',
    notes: 'You may call, text, or contact us through AirBNB. We speak both Mandarin and English. Please lock the doors upon exiting or checking out of the building. Please also keep the house clean. Please No Pets, and No Smoking.',
    area: 'Monrovia',
    price: 79,
    people: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1.5,
    fullHome: false,
    privateRoom: true,
    privateBath: true
  },
  {
    address: '516 West Bencamp Street, San Gabriel, CA 91776, US',
    title: 'Modern Townhome located in San Gabriel',
    link: 'https://www.airbnb.com/rooms/19915162',
    summary: 'Brand New, Luxurious San Gabriel Home at Good Location',
    description: 'Home has one bedroom downstairs with a full bath. Master bedroom is upstairs comes with a jacuzzi tub plus standing shower. Beautiful new granite counter top in the kitchen. Brand new refrigerator, washer and dryer are included. The home itself is in a very convenient location. Close to banks, bus, many restaurants and shops. Must see to truely appreciate how wonderful this home is.',
    access: 'As soon as you enter the home, you will notice the wide open space of the living room. Just to the right is kitchen. Both is very spacious and may fit many people. Each room is well equipped with amenities and comfortable bedding. There is beautiful granite counter tops and wonderfully bright walls to give the home a cozy atmosphere. Central AC gives the home a nice touch.',
    neighborhood: 'The neighborhood is nice and cozy. The streets are relatively narrow, but they are uncongested enough to lets cars through.',
    transportation: 'The home is very close to many Chinese plazas, restaurants, shopping centers, and banks. Guests will never feel they need to go far for food.',
    notes: 'You may contact us via call, text, or e-mail, or through airbnb. Able to speak both Mandarin and English. Please lock the door when you leave, and close the garage door as well. Keep the garage remote and house keys secure as well please.',
    area: 'San Gabriel',
    price: 268,
    people: 6,
    bedrooms: 3,
    beds: 3,
    bathrooms: 3,
    fullHome: true,
    privateRoom: true,
    privateBath: true
  },
  // {
  //   address: '',
  //   link: '',
  //   summary: '',
  //   description: '',
  //   access: '',
  //   neighborhood: '',
  //   transportation: '',
  //   notes: '',
  //   area: '',
  //   price: ,
  //   people: ,
  //   bedrooms: ,
  //   beds: ,
  //   bathrooms: ,
  //   fullHome: ,
  //   privateRoom: ,
  //   privateBath: 
  // },
];

homeArray.forEach(home => {
  Home.create(home, (err, home) => {
    if (err) { console.log('Error in creating homes in DB', err); }
  });
});