// Script to add homes to the database
const mongoose = require('mongoose');
const schemas = require('./schemas.js');
let Home = schemas.Home;

mongoose.connect('mongodb://localhost/applehomes');

const homeArray = [
  {
    address: '527 Windsor Road, Arcadia, CA 91007',
    summary: 'This home near 210 freeway convent. Features two queen size bedrooms on the second floor. Both contains a very cozy queen size double bed with memory form mattress and pillow.',
    description: 'The house is Ranch-style, has two bedrooms, both including a queen sized bed. The second floor of the private space, clean and tidy, the bed is soft and comfortable, cooking convenience, washing hot water, quiet environment, easy parking, convenient transportation. 10 minutes walk. It is a few minutes drive to Chinese supermarkets, cinemas malls, hospitals and hotels. 2 rooms can accommodate 2-4 people for small families to travel to rent. The location is close to big shopping mall and not far from the 210 free way. It is comfy house to stay for vacation. The room is nice and clean. You are given access to two bedrooms in a three bedroom house.',
    access: 'Full access to their respective rooms within the house, located on the second story of the building. Guests may also use rest of living space within the house including: Living room, kitchen (this includes also cookware, utensils, plates, etc).',
    neighborhood: 'Our house is extremely close to the 210 Freeway. The house is close to the park and the golf course, the traffic will be quiet, from the bank, post office, restaurant, light rail station, bus station. Airport 40 minutes drive to Universal Studios, Hollywood. Disneyland 30 minutes by car.',
    transportation: 'On the 210 high speed, take the light rail and the bus will be to Los Angeles Airport about 40 minutes to Universal Studios Hollywood and Disneyland 30 minutes by car. A few minutes to reach the nearby banks, post offices, restaurants, hotels, barber shop , The Chinese supermarket, the school library, the racecourse, the hospital, the shops, the department stores, the cinemas, the city hall, etc. Drive to the Gulf of Ireland about 60 minutes by car to the Las Vegas about 4 hours by car.good location close shopping mall Park, golf course',
    notes: 'You may call, text, or contact us through AirBNB. We speak both Mandarin and English. Please lock the doors upon exiting or checking out of the building. Please also keep the house clean.',
    area: 'Arcadia',
    price: 999,
    people: 4,
    beds: 2,
    bedrooms: 2,
    bathrooms: 1,
    fullHome: false,
    privateRoom: true,
    privateBath: true
  },
  {
    address: '1937 Strathmore Ave, San Gabriel , CA 91776',
    summary: 'This listing is for one bedroom in a 5 bedroom house',
    description: 'This room has a queen size bed , and can accommodate 2 guests, Great location, walking distance to shopping and restaurants. The mattress and bedding are completely accord with human body sleep designed comfortable activities, absolutely let you have a high-quality sleep experience. The room is also equipped with a small refrigerator, kitchen dining room guests can be used at any time. Kitchen double refrigerator capacity. Inside / outside the room for guest parking. You can walk to the Chinese supermarket shopping malls, restaurants, this is  most concentrated residential area.',
    access: 'Access to their respective rooms and rest of living space including: living room, kitchen, washer, dryer, parking space, etc.',
    neighborhood: 'Location is very convenient with several Chinese business and locations around the area. There are several around the Chinese supermarket, as well as a large variety of restaurants around there several star hotels. Enjoying a vacation with friends can be convenient. Located near the 10th high-speed travel, it is convenient to travel to many places, including: the heart of LA, Disneyland, Hollywood, and other major cities and sites.',
    transportation: 'Being near the freeway, our location is very convenient to travel to many places. There are bus stations located nearby and the airport only takes about 35 minutes to get to. To Hollywood Universal Pictures, Disneyland about 25-30 minutes by car.',
    notes: 'You may contact me via call, text, or e-mail, or through airbnb. Able to speak both Mandarin and English. Please lock the door when you leave, and close the garage door as well. Keep the garage remote and house keys secure as well please.',
    area: 'San Gabriel',
    price: 999,
    people: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    fullHome: false,
    privateRoom: true,
    privateBath: false
  },
  {
    address: '306 West Lime Avenue, Monrovia, CA 91016',
    summary: 'Double story house with 2 private rooms available for use. There is plenty of privacy and includes 1.5 bathrooms as well. Comes equipped with high speed internet access, dedicated parking space, hotel standard bedding, as well as cooking utensils, equipment, and laundry. Convenient and comfortable, as well as being on minutes away from Old Town Monrovia. Every Friday, experience the well known Monrovia farmers market and entertainment only minutes away from your doorstep.',
    description: 'Space independence, this house has three rooms, the master bedroom when there is no time to live. So the entire house from the parking garage, kitchen dining room, living room laundry room easy to use. All meal cooking utensils are complete. A 10-minute walk from Monrovia\'s old town\'s central business street. On the street cinema supermarkets and a variety of styles of cuisine are everywhere. 2 rooms close together, bedding clean and comfortable. The rooms are warm and romantic.',
    access: 'Full access to the house and their respective rooms.',
    neighborhood: 'Only a few minutes walk to the library, park, cinema, supermarket, gymnasium, and bank. As well as a variety of restaurants nearby to cater to your tastes. Everything you need is only a few minutes walk. Experience american culture by partaking in the local festivities every Friday at the night market in Old Town Monrovia. Located in a quiet and friendly neighborhood, unwind in the relaxed atmosphere the city has to offer.',
    transportation: 'Location is only a few minutes away from the 210 high-speed freeway. The gold line metro is only a few minutes away by car, or about 18 minutes walking. The Los Angeles International Airport is about 45 minutes,  Hollywood Universal Studios is about 30 minutes away, and Disneyland is about 45 minutes away',
    notes: 'You may contact me via call, text, e-mail, or through airbnb. Able to speak both Mandarin and English. Please lock the door when you leave.',
    area: 'Monrovia',
    price: 999,
    people: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1.5,
    fullHome: true,
    privateRoom: true,
    privateBath: true
  },
  {
    address: '580 North Atlantic Blvd Ut 433, Monterey Park, CA 91754',
    summary: 'Beautiful and newly furnished hotel-esque living space located right above the lively Monterey Park Times Square. Enjoy comfort in our clean and comfortable living space perfect for families or groups. If you\'re in the mood for food; conveniently only a few minutes by walk, you may enjoy several varieties of Asian-themed restaurants to choose from right below. The times square also hosts a large selection of entertainment choices to choose such as a 24 hour gym, AMC cinema, and games to play.',
    description: 'Fully furnished 2 Bedroom, 2 Bathroom lovely home complete with new furniture, a large king and two queen sized beds. Kitchen is fully stacked with cooking equipment, dishes, and eating utensils.  Included is also: a complete washer and dryer set in the house, two private parking spaces, and free public swimming pool to enjoy for those upcoming hot days. Downstairs in the times square features a variety of food and entertainment choices only a few minutes walk.',
    access: 'Full private access to entire apartment.',
    neighborhood: 'Our lovely home is not only conveniently located next to the 10 high speed freeway, but also conveniently above a plaza hosting several forms of Asian-style cuisine and desserts. Not only cuisine, but there are several stores you can shop at, cafes to relax in, a 24 hour fitness gym for members, and also a large AMC theater. If you ever want to explore the heart of LA, we\'re only 20 minutes away by freeway. The apartment building also features a free public swimming pool available for apartment tenants and guests on the 3rd floor.',
    transportation: 'Easy access to 10 FWY 2 minutes to go to Highway 10, about 30 minutes to Los Angeles International Airport, about 26 minutes to Universal Studios, about 40 minutes to Disneyland. From Highway 10 to the east to the Outlet Mall, and Las Vegas. West to the city center and so on.',
    notes: 'You may contact us through phone, text, or Airbnb. We speak English and Mandarin. Please lock the door when you exit. Turn off all lights when not in use either. No Smoking. Thank you.',
    area: 'Monterey Park',
    price: 999,
    people: 6,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    fullHome: true,
    privateRoom: true,
    privateBath: true
  },
  {
    address: '600 North Atlantic Blvd Ut 309, Monterey Park, CA 91754',
    summary: 'New Condo in City of Monterey Park. Atlantic Time Square brings excitement like New York City Time Square& more. This urban lifestyle featuring 210 luxury condo units with attractive Paseo design. Residence unit from 2nd floor to 6th floor. Unique features includes: modern spacious living area and bath room; large kitchen space; granite counter tops; top of the line stainless appliances; washer and dryer space; circular design entrance. Balconies in all units. Large windows for great views.',
    description: 'This house it is easily accommodates a whole family or roommates to share ,located at the intersection of Atlantic Blvd and Hellman and just one block from freeway 10.',
    access: 'Full private access to entire apartment.',
    neighborhood: 'This is Charming and modern area. Club house, swimming pool and courtyard are some amenities for residence. Ground level gives you endless amenities, 24 house fitness center, restaurants, Supermarket,shopping, AMC Theaters and much more.',
    transportation: 'Easy access to 10 FWY 2 minutes to go to Highway 10, about 30 minutes to Los Angeles International Airport, about 26 minutes to Universal Studios, about 40 minutes to Disneyland. From Highway 10 to the east to the Outlet Mall, and Las Vegas. West to the city center and so on.',
    notes: '1)Please lock the doors when you leave the apartment. 2)Clothes may not be hanged outside on the balcony. 3)Please clean cookware and utensils after use. 4)Turn off water and gas when not in use. 5)Please turn off the lights and central AC when you leave. 6)Please do not leave children unsupervised on the balcony in case of injury. You may contact us through phone, text, or airbnb message. We speak both English and Mandarin.',
    area: 'Monterey Park',
    price: 999,
    people: 6,
    bedrooms: 3,
    beds: 3,
    bathrooms: 2.5,
    fullHome: true,
    privateRoom: true,
    privateBath: true
  },
  {
    address: '306 S 1St Ave #102, Arcadia, CA 91006',
    summary: 'Spacious, bright and comfortable master bedroom, open the window to see the Arab-Israeli city of San Gabriel and the beauty of the mountain scenery. Furnished with a large king sized bed. It is within walking distance to the Park Golf Course, Library, School, Hospital, as well as the Santa Anita mall, and all kinds of summer camp schools. The gold-line subway station is within walking distance to all kinds of food, Chinese supermarkets and night markets. Nearby, lies the high speed 210 freeway.',
    description: 'The master bedroom is bright and spacious with a private bathroom and a balcony. There is plenty of parking in the basement and the lift is accessible. Both the kitchen and the living room is bright and spacious as well.',
    access: '',
    neighborhood: 'We are located near many restaurants down on Huntington and 1st street. We are also right next to the large Arcadia park and golf course for all your exercise needs. Occasionally, there is a farmers market near the 24 hour fitness gym on Fridays, down on 1st st.',
    transportation: 'Being only a few minutes from the 210 high-speed freeway, the East can go to Las Vegas, West to Los Angeles city center, Los Angeles International Airport, Universal Studios, are only 30-40 minutes. To Disneyland is only 40 minutes or so. East to Outlets but also 50 minutes by car. A few minutes walk to the gold line metro along first street, you\'ll be able to explore the heart of LA. Travelling is very convenient.',
    notes: 'Please throw away garbage in the garbage bags and lock the door when leaving. Turn off lights when not in use. No pets, Non smoking. Thank you.',
    area: 'Arcadia',
    price: 999,
    people: 3,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    fullHome: false,
    privateRoom: true,
    privateBath: true
  },
  {
    address: '306 S 1St Ave #102, Arcadia , CA 91006',
    summary: 'New nice modern luxury condo in prime location of Arcadia, open floor plan granite countertops . Each room comes with a desk and chair. There has plenty spacious, especially downstairs in the living room and kitchen area.close to restaurants, park ,golf course.',
    description: 'The Luxury Mix use property total is 2000 sqft , this great complex is in the highly desirable IL Villagio community of Arcadia, there is a fitness center, elevator and gated 2-assigned parking in the community. All bedrooms upstairs, has family room , living room, master suite and walk-in Closet and wonderfully lays out into a very comfortable open floor plan , features elegant crown molding,center air, wood floors downstairs, counter top in gourmet kitchen and bathroom, the rooms are bright and big spacious. Though both rooms share a bathroom, there is an additional .5 bathroom downstairs as well. Both rooms also have a balcony in case you want to step outside for a bit of fresh air. Located below the building, in the lies a garage with a washer and dryer if you need to wash your clothes or park a car.',
    access: 'Full access to their respective rooms within the location, including: Parking, kitchen (cooking utensils included), living room, laundry, wine storage machines, fresh cabinets, etc, can be used. Wi-Fi high-speed Internet access. Please note: These are private rooms only.',
    neighborhood: 'Please google, Mapquest and GPS navigation device, map Biok:567D6. We\'re located near many restaurants down on Huntington and 1st street. We are also right next to the large Arcadia park and golf course for all your exercise needs. Occasionally, there is a farmers market near the 24 hour fitness gym on Fridays, down on 1st st.',
    transportation: 'Being only a few minutes from the 210 high-speed freeway, the East can go to Las Vegas, West to Los Angeles city center, Los Angeles International Airport, Universal Studios, are only 30-40 minutes. To Disneyland is only 40 minutes or so. East to Outlets but also 50 minutes by car. A few minutes walk to the gold line metro along first street, Travelling is very convenient.',
    notes: 'You may call, text, e-mail, or contact us through Airbnb. Can speak both English and Mandarin.Please throw away garbage in the garbage bags and lock the door when leaving.',
    area: 'Arcadia',
    price: 999,
    people: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1.5,
    fullHome: true,
    privateRoom: true,
    privateBath: true
  },
  {
    address: '304 West Lime Avenue Unit 1, Monrovia, CA 91016',
    summary: 'Our convenient and comfortable home is located near the heart of Old Town Monrovia. There, you can explore and dine on the many various styles of restaurants and food around, as well as spend a lovely evening date watching movies or walking around the park. The master bedroom is fully furnished with a large queen sized bed. Downstairs features a large and spacious living area perfect for work space as well as relaxation. Kitchen is fully equipped with cooking equipment, dishware, and utensils.',
    description: 'You\'ll be given access the master bedroom of our home. Comes complete with a private bathroom inside as well. Our space is located in a very quiet and family oriented neighborhood. You\'ll be given total peace and quiet to enjoy and relax all that the nearby streets have to offer. Being only a few minutes away by walk, Old Town Monrovia features a wide variety of activities and shops to enjoy. Every Friday, you\'ll be able to enjoy the Monrovia Old Town night market featuring an even more wide variety of street food, desserts, and hand made crafts. The streets become very bustling and lively, perfect for dates and casual hang outs with friends, while still remaining very quiet and peaceful during your stays at our home.',
    access: 'Full access to 1st floor and respective room on 2nd floor. Wi-Fi included.',
    neighborhood: 'Only a few minutes walk to the library, park, cinema, supermarket, gymnasium, and bank. As well as a variety of restaurants nearby to cater to your tastes. Everything you need is only a few minutes walk. Experience american culture by partaking in the local festivities every Friday at the night market in Old Town Monrovia. Located in a quiet and friendly neighborhood, unwind in the relaxed atmosphere the city has to offer.',
    transportation: 'Location is only a few minutes away from the 210 high-speed freeway. The gold line metro is only a few minutes away by car, or about 18 minutes walking. The Los Angeles International Airport is about 45 minutes,  Hollywood Universal Studios is about 30 minutes away, and Disneyland is about 45 minutes away.',
    notes: 'Please lock the door when you. Please turn off the lights if not in use. No pets. Non smoking Thank you. You may contact me via call, text, e-mail, or through airbnb. Able to speak both Mandarin and English.',
    area: 'Monrovia',
    price: 999,
    people: 3,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    fullHome: false,
    privateRoom: true,
    privateBath: true
  },
  {
    address: '304 West Lime Avenue Unit 2, Monrovia, CA 91016',
    summary: 'Our convenient and comfortable home is located near the heart of Old Town Monrovia. There, you can explore and dine on the many various styles of restaurants and food around, as well as spend a lovely evening date watching movies or walking around the park. The room is fully furnished with a large queen sized bed. Downstairs features a large and spacious living area perfect for work space as well as relaxation. Kitchen is fully equipped with cooking equipment, dishware, and utensils.',
    description: 'Our space is located in a very quiet and family oriented neighborhood. You\'ll be given total peace and quiet to enjoy and relax all that the nearby streets have to offer. Being only a few minutes away by walk, Old Town Monrovia features a wide variety of activities and shops to enjoy. Every Friday, you\'ll be able to enjoy the Monrovia Old Town night market featuring an even more wide variety of street food, desserts, and hand made crafts. The streets become very bustling and lively, perfect for dates and casual hang outs with friends, while still remaining very quiet and peaceful during your stays at our home.',
    access: 'Access to 1st story and their respective room on the 2nd floor. 1.5 Bathroom is shared if there are other quests. Wi-Fi included',
    neighborhood: 'Only a few minutes walk to the library, park, cinema, supermarket, gymnasium, and bank. As well as a variety of restaurants nearby to cater to your tastes. Everything you need is only a few minutes walk. Experience american culture by partaking in the local festivities every Friday at the night market in Old Town Monrovia. Located in a quiet and friendly neighborhood, unwind in the relaxed atmosphere the city has to offer.',
    transportation: 'Location is only a few minutes away from the 210 high-speed freeway. The gold line metro is only a few minutes away by car, or about 18 minutes walking. The Los Angeles International Airport is about 45 minutes,  Hollywood Universal Studios is about 30 minutes away, and Disneyland is about 45 minutes away.',
    notes: 'You may contact me via call, text, e-mail, or through airbnb. Able to speak both Mandarin and English. Please lock the door when you. Please turn off the lights if not in use. No pets. Non smoking. Thank you.',
    area: 'Monrovia',
    price: 999,
    people: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1.5,
    fullHome: false,
    privateRoom: true,
    privateBath: true
  },
  {
    address: '165 Bonita St #A, Arcadia , CA 91006',
    summary: 'Arcadia City Center is within walking distance to the subway station and bus station. Schools, parks, gold courses, libraries are within walking distance as well. There are Chinese restaurants is in the vicinity of the supermarket. The house is in a very quiet neighborhood. There is a sofa/folding bed that is suitable for families and couples. It has its own private bathroom, kitchen, parking garage, and laundry.',
    description: 'Easy parking. Kitchen and laundry room are available for anyone to use. There are fragent fruit trees in the peaceful, quiet stone garden. There is a spacious living room.',
    access: 'Parking Garage, Laundry room, kitchen, dining room, living room, lounge, front and rear garden areas can be accessed.',
    neighborhood: 'Home in Arcadia, between the 1St and 2St, is a quiet place, within walking distance to the nearby school, Methodist Hospital, post office, Bank, Metro bus public transport, Park Golf course, and a variety of restaurants and Chinese supermarkets. Occasionally there will be American-style night market.',
    transportation: '5 minutes on the 210 Freeway, East Las Vegas, 35 minutes to downtown Los Angeles to the West. 45 minutes from the airport, about 35 minutes from Universal Studios Hollywood, about 45 minutes from Disneyland, about 50 minutes from auto outlet. A few minutes walk to a nearby subway station and bus station.',
    notes: 'Please lock the door and garage door when leaving. Turn off the gas stove in the kitchen, as well as the light. 12:00 minutes later on the cars cannot be parked on the roadside.',
    area: 'Arcadia',
    price: 999,
    people: 3,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    fullHome: true,
    privateRoom: true,
    privateBath: true
  },
  {
    address: '580 North Atlantic Boulevard #213, Monterey Park , CA',
    summary: 'Beautiful and newly furnished hotel-esque living space located right above the lively Monterey Park Times Square. Enjoy comfort in our clean and comfortable living space perfect for families or groups. If you\'re in the mood for food; conveniently only a few minutes by walk, you may enjoy several varieties of Asian-themed restaurants to choose from right below. The times square also hosts a large selection of entertainment choices to choose such as a 24 hour gym, AMC cinema, and games to play.',
    description: 'Fully furnished 3 Bedroom, 2.5 Bathroom lovely home complete with new furniture, a large king and two queen sized beds. Kitchen is fully stacked with cooking equipment, dishes, and eating utensils.  Included is also: a complete washer and dryer set in the house, two private parking spaces, and free public swimming pool to enjoy for those upcoming hot days. Downstairs in the times square features a variety of food and entertainment choices only a few minutes walk.',
    access: 'Full private access to entire apartment.',
    neighborhood: 'Our lovely home is not only conveniently located next to the 10 high speed freeway, but also conveniently above a plaza hosting several forms of Asian-style cuisine and desserts. Not only cuisine, but there are several stores you can shop at, cafes to relax in, a 24 hour fitness gym for members, and also a large AMC theater. If you ever want to explore the heart of LA, we\'re only 20 minutes away by freeway. The apartment building also features a free public swimming pool available for apartment tenants and guests on the 3rd floor.',
    transportation: 'Easy access to 10 FWY 2 minutes to go to Highway 10, about 30 minutes to Los Angeles International Airport, about 26 minutes to Universal Studios, about 40 minutes to Disneyland. From Highway 10 to the east to the Outlet Mall, and Las Vegas. West to the city center and so on.',
    notes: 'You may contact us through phone, text, or Airbnb. We speak English and Mandarin. Please lock the door when you exit. Turn off all lights when not in use either. No Smoking. Thank you',
    area: 'Monterey Park',
    price: 999,
    people: 6,
    bedrooms: 3,
    beds: 3,
    bathrooms: 2.5,
    fullHome: true,
    privateRoom: true,
    privateBath: true
  },
  {
    address: '50 Alice Street Unit C, Arcadia, CA 91006',
    summary: 'This home features large rooms with clean and comfortable beds. We may had additional beds to accommodate more people. We also have makeup and bathroom facilities. If you are exploring the city, the home is within walking distance to the subway station. There is a post office, bank, Arcadia High School, libraries, park, and golf course all nearby. You will feel very secure in this home!',
    description: 'This home has enough space for a family. The apartment unit is beyond a gate so there is extra security in an already safe, peaceful, quiet neighborhood. There are specific parking spaces underground for the unit. Each bedroom has their own restroom. The master bedroom is very spacious.',
    access: 'Conveniently located Arcadia park golf course restaurants and shops. Come with two car parking garage.',
    neighborhood: 'The neighborhood is nice and quiet.',
    transportation: 'There are many plazas that are close by. The 210 freeway is only about 7 minutes away.',
    notes: '',
    area: 'Arcadia',
    price: 999,
    people: 6,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2.5,
    fullHome: true,
    privateRoom: true,
    privateBath: true
  }
];

homeArray.forEach(home => {
  Home.create(home, (err, home) => {
    if (err) { console.log('Error in creating homes in DB', err); }
  });
});